background = #050A2D
foreground = #AAC5DD
cursor-color = #E4F2FC
selection-background = #0E285B
selection-foreground = #E4F2FC

palette = 0=#050A2D
palette = 1=#F1758A
palette = 2=#63D1A7
palette = 3=#E8C47F
palette = 4=#4995DD
palette = 5=#C678DD
palette = 6=#3FD4E8
palette = 7=#AAC5DD
palette = 8=#245D9A
palette = 9=#FF91A0
palette = 10=#8FE8C4
palette = 11=#F5D99E
palette = 12=#6FB4F2
palette = 13=#DA9AF0
palette = 14=#6FE4F2
palette = 15=#E4F2FC