;;; ocean-night-theme.el --- Deep navy + ocean blue Emacs theme -*- lexical-binding: t; -*-

(deftheme ocean-night
  "Ocean Night - deep navy background with ocean blue accents.")

(let ((ocn-bg          "#050A2D")
      (ocn-bg-deep     "#02040C")
      (ocn-bg-soft     "#0E285B")
      (ocn-fg          "#AAC5DD")
      (ocn-fg-bright   "#E4F2FC")
      (ocn-accent      "#4995DD")
      (ocn-cyan        "#3FD4E8")
      (ocn-sky         "#86CEE8")
      (ocn-muted       "#245D9A")
      (ocn-green       "#63D1A7")
      (ocn-yellow      "#E8C47F")
      (ocn-red         "#F1758A")
      (ocn-orange      "#EF9766")
      (ocn-magenta     "#C678DD"))

  (custom-theme-set-faces
   'ocean-night

   `(default ((t (:background ,ocn-bg :foreground ,ocn-fg))))
   `(cursor ((t (:background ,ocn-fg-bright :foreground ,ocn-bg))))
   `(region ((t (:background ,ocn-bg-soft :foreground ,ocn-fg-bright))))
   `(secondary-selection ((t (:background ,ocn-bg-soft))))
   `(highlight ((t (:background ,ocn-bg-soft :foreground ,ocn-fg-bright))))
   `(lazy-highlight ((t (:background ,ocn-accent :foreground ,ocn-bg))))
   `(isearch ((t (:background ,ocn-sky :foreground ,ocn-bg-deep))))
   `(isearch-fail ((t (:background ,ocn-red :foreground ,ocn-bg-deep))))
   `(query-replace ((t (:inherit isearch))))

   `(minibuffer-prompt ((t (:foreground ,ocn-sky))))
   `(echo-area-invalid ((t (:foreground ,ocn-red))))
   `(trailing-whitespace ((t (:background ,ocn-red :foreground ,ocn-bg))))

   `(font-lock-comment-face ((t (:foreground ,ocn-muted :italic t))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,ocn-muted :italic t))))
   `(font-lock-doc-face ((t (:foreground ,ocn-muted))))
   `(font-lock-string-face ((t (:foreground ,ocn-green))))
   `(font-lock-constant-face ((t (:foreground ,ocn-orange))))
   `(font-lock-number-face ((t (:foreground ,ocn-orange))))
   `(font-lock-keyword-face ((t (:foreground ,ocn-magenta))))
   `(font-lock-builtin-face ((t (:foreground ,ocn-cyan))))
   `(font-lock-function-name-face ((t (:foreground ,ocn-sky))))
   `(font-lock-variable-name-face ((t (:foreground ,ocn-fg))))
   `(font-lock-type-face ((t (:foreground ,ocn-yellow))))
   `(font-lock-preprocessor-face ((t (:foreground ,ocn-yellow))))
   `(font-lock-negation-char-face ((t (:foreground ,ocn-sky))))

   `(link ((t (:foreground ,ocn-cyan :underline t))))
   `(link-visited ((t (:foreground ,ocn-accent :underline t))))
   `(button ((t (:inherit link))))
   `(header-line ((t (:background ,ocn-bg-deep :foreground ,ocn-fg-bright))))
   `(mode-line ((t (:background ,ocn-bg-soft :foreground ,ocn-fg :box nil))))
   `(mode-line-inactive ((t (:background ,ocn-bg-deep :foreground ,ocn-muted :box nil))))
   `(mode-line-highlight ((t (:background ,ocn-accent :foreground ,ocn-fg-bright))))
   `(mode-line-buffer-id ((t (:foreground ,ocn-sky :weight bold))))
   `(mode-line-emphasis ((t (:foreground ,ocn-fg-bright :weight bold))))

   `(vertical-border ((t (:foreground ,ocn-bg-soft))))
   `(fringe ((t (:background ,ocn-bg :foreground ,ocn-muted))))
   `(linum ((t (:background ,ocn-bg :foreground ,ocn-muted))))
   `(line-number ((t (:background ,ocn-bg :foreground ,ocn-muted))))
   `(line-number-current-line ((t (:background ,ocn-bg-soft :foreground ,ocn-sky))))
   `(hl-line ((t (:background ,ocn-bg-soft))))
   `(hl-line-face ((t (:background ,ocn-bg-soft))))

   `(show-paren-match ((t (:background ,ocn-accent :foreground ,ocn-fg-bright))))
   `(show-paren-mismatch ((t (:background ,ocn-red :foreground ,ocn-bg))))

   `(success ((t (:foreground ,ocn-green))))
   `(warning ((t (:foreground ,ocn-yellow))))
   `(error ((t (:foreground ,ocn-red :weight bold))))

   `(widget-field ((t (:background ,ocn-bg-deep :foreground ,ocn-fg))))
   `(completions-first-difference ((t (:foreground ,ocn-cyan :weight bold))))
   `(completions-common-part ((t (:foreground ,ocn-fg))))
   `(completions-annotations ((t (:foreground ,ocn-muted))))

   `(company-tooltip ((t (:background ,ocn-bg-deep :foreground ,ocn-fg))))
   `(company-tooltip-selection ((t (:background ,ocn-accent :foreground ,ocn-fg-bright))))
   `(company-tooltip-annotation ((t (:foreground ,ocn-muted))))
   `(company-scrollbar-fg ((t (:background ,ocn-muted))))
   `(company-scrollbar-bg ((t (:background ,ocn-bg-deep))))
   `(company-preview ((t (:background ,ocn-bg-soft))))
   `(company-preview-common ((t (:background ,ocn-bg-soft :foreground ,ocn-cyan))))

   `(treemvc-directory-face ((t (:foreground ,ocn-sky :weight bold))))
   `(dired-directory ((t (:foreground ,ocn-sky :weight bold))))
   `(dired-header ((t (:foreground ,ocn-fg-bright :weight bold))))
   `(dired-mark ((t (:foreground ,ocn-magenta))))
   `(dired-symlink ((t (:foreground ,ocn-cyan))))

   `(magit-section-heading ((t (:foreground ,ocn-sky :weight bold))))
   `(magit-diff-added ((t (:foreground ,ocn-green))))
   `(magit-diff-removed ((t (:foreground ,ocn-red))))
   `(magit-diff-removed-highlight ((t (:background ,ocn-bg-deep :foreground ,ocn-red))))
   `(magit-diff-added-highlight ((t (:background ,ocn-bg-deep :foreground ,ocn-green))))
   `(magit-branch ((t (:foreground ,ocn-magenta))))
   `(magit-dimmed ((t (:foreground ,ocn-muted))))

   `(git-commit-summary ((t (:foreground ,ocn-fg-bright :weight bold))))
   `(git-commit-message ((t (:foreground ,ocn-fg))))
   `(markdown-header-face ((t (:foreground ,ocn-sky :weight bold))))
   `(markdown-bold-face ((t (:foreground ,ocn-fg-bright :weight bold))))
   `(markdown-italic-face ((t (:foreground ,ocn-fg :italic t))))
   `(markdown-code-face ((t (:background ,ocn-bg-deep :foreground ,ocn-green))))
   `(markdown-link-face ((t (:foreground ,ocn-cyan :underline t))))
   `(org-level-1 ((t (:foreground ,ocn-sky :weight bold :height 1.2))))
   `(org-level-2 ((t (:foreground ,ocn-accent :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,ocn-green :weight bold))))
   `(org-level-4 ((t (:foreground ,ocn-yellow))))
   `(org-date ((t (:foreground ,ocn-cyan :underline t))))
   `(org-link ((t (:foreground ,ocn-cyan :underline t))))
   `(org-tag ((t (:foreground ,ocn-muted))))
   `(org-todo ((t (:foreground ,ocn-yellow :weight bold))))
   `(org-done ((t (:foreground ,ocn-green :weight bold))))
   `(org-quote ((t (:foreground ,ocn-muted :italic t))))
   `(org-block ((t (:background ,ocn-bg-deep))))
   `(org-block-begin-line ((t (:background ,ocn-bg-deep :foreground ,ocn-muted))))

   `(diff-added ((t (:foreground ,ocn-green))))
   `(diff-removed ((t (:foreground ,ocn-red))))
   `(diff-changed ((t (:foreground ,ocn-orange))))
   `(diff-header ((t (:foreground ,ocn-sky))))
   `(diff-hunk-header ((t (:foreground ,ocn-accent :weight bold))))
   `(diff-file-header ((t (:foreground ,ocn-fg-bright :weight bold))))

   `(ediff-current-diff-A ((t (:background ,ocn-bg-deep :foreground ,ocn-red))))
   `(ediff-current-diff-B ((t (:background ,ocn-bg-deep :foreground ,ocn-green))))
   `(ediff-fine-diff-A ((t (:background ,ocn-bg-soft :foreground ,ocn-red))))
   `(ediff-fine-diff-B ((t (:background ,ocn-bg-soft :foreground ,ocn-green))))

   `(term ((t (:foreground ,ocn-fg :background ,ocn-bg))))
   `(term-color-black ((t (:foreground ,ocn-bg))))
   `(term-color-red ((t (:foreground ,ocn-red))))
   `(term-color-green ((t (:foreground ,ocn-green))))
   `(term-color-yellow ((t (:foreground ,ocn-yellow))))
   `(term-color-blue ((t (:foreground ,ocn-accent))))
   `(term-color-magenta ((t (:foreground ,ocn-magenta))))
   `(term-color-cyan ((t (:foreground ,ocn-cyan))))
   `(term-color-white ((t (:foreground ,ocn-fg))))

   `(ansi-color-black ((t (:foreground ,ocn-bg :background ,ocn-bg))))
   `(ansi-color-red ((t (:foreground ,ocn-red :background ,ocn-red))))
   `(ansi-color-green ((t (:foreground ,ocn-green :background ,ocn-green))))
   `(ansi-color-yellow ((t (:foreground ,ocn-yellow :background ,ocn-yellow))))
   `(ansi-color-blue ((t (:foreground ,ocn-accent :background ,ocn-accent))))
   `(ansi-color-magenta ((t (:foreground ,ocn-magenta :background ,ocn-magenta))))
   `(ansi-color-cyan ((t (:foreground ,ocn-cyan :background ,ocn-cyan))))
   `(ansi-color-white ((t (:foreground ,ocn-fg :background ,ocn-fg))))
   `(ansi-color-bright-black ((t (:foreground ,ocn-muted :background ,ocn-muted))))
   `(ansi-color-bright-red ((t (:foreground ,"#FF91A0" :background ,"#FF91A0"))))
   `(ansi-color-bright-green ((t (:foreground ,"#8FE8C4" :background ,"#8FE8C4"))))
   `(ansi-color-bright-yellow ((t (:foreground ,"#F5D99E" :background ,"#F5D99E"))))
   `(ansi-color-bright-blue ((t (:foreground ,"#6FB4F2" :background ,"#6FB4F2"))))
   `(ansi-color-bright-magenta ((t (:foreground ,"#DA9AF0" :background ,"#DA9AF0"))))
   `(ansi-color-bright-cyan ((t (:foreground ,"#6FE4F2" :background ,"#6FE4F2"))))
   `(ansi-color-bright-white ((t (:foreground ,ocn-fg-bright :background ,ocn-fg-bright))))

   `(tooltip ((t (:background ,ocn-bg-deep :foreground ,ocn-fg))))
   `(tty-menu-enabled-face ((t (:background ,ocn-bg-deep :foreground ,ocn-fg))))
   `(tty-menu-selected-face ((t (:background ,ocn-accent :foreground ,ocn-fg-bright))))

   `(minibuffer-notice ((t (:foreground ,ocn-green))))
   `(php-constructor-face ((t (:foreground ,ocn-magenta))))
   `(web-mode-html-tag-face ((t (:foreground ,ocn-sky))))
   `(web-mode-html-tag-bracket-face ((t (:foreground ,ocn-muted))))
   `(web-mode-html-attr-name-face ((t (:foreground ,ocn-fg-bright))))

   `(error-face ((t (:foreground ,ocn-red :weight bold))))
   `(button-tag ((t (:foreground ,ocn-sky :weight bold))))
   `(whitespace-space ((t (:foreground ,ocn-bg-soft))))
   `(whitespace-tab ((t (:foreground ,ocn-bg-soft))))
   `(whitespace-newline ((t (:foreground ,ocn-bg-soft))))

   `(window-divider ((t (:foreground ,ocn-bg-soft))))
   `(scroll-bar ((t (:background ,ocn-bg-deep :foreground ,ocn-muted)))))

(custom-theme-set-variables
 'ocean-night
 '(ansi-color-names-vector
   [,ocn-bg ,ocn-red ,ocn-green ,ocn-yellow ,ocn-accent ,ocn-magenta ,ocn-cyan ,ocn-fg])))

(provide-theme 'ocean-night)
;;; ocean-night-theme.el ends here